
CREATE TABLE UGYFEL
(
    LOGIN varchar(32) PRIMARY KEY,
    EMAIL varchar(64) MASKED WITH (FUNCTION = 'email()'),
    NEV varchar(64) MASKED WITH (FUNCTION = 'partial(1,"XXX",1)'),
    SZULEV int MASKED WITH (FUNCTION = 'random(1900,2025)'),
    NEM varchar(1) MASKED WITH (FUNCTION = 'default()')
);
INSERT INTO UGYFEL
(LOGIN, EMAIL, NEV, SZULEV, NEM)
VALUES
('adam1', 'ádám.kiss@mail.hu', 'Kiss Ádám', 1991, 'F'),
('adam3', 'adam3@gmail.com', 'Barkóci Ádám', 1970, 'F'),
('adam4', 'ádám.bieniek@mail.hu', 'Bieniek Ádám', 1976, 'F'),
('agnes', 'agnes@gmail.com', 'Lengyel Ágnes', 1979, 'N'),
('agnes3', 'agnes3@gmail.com', 'Hartyánszky Ágnes', 1967, 'N'),
('AGNESH', 'AGNESH@gmail.com', 'Horváth Ágnes', 1981, 'N'),
('AGNESK', 'AGNESK@gmail.com', 'Kovács Ágnes', 1988, 'N'),
('akos', 'ákos.bíró@mail.hu', 'Bíró Ákos', 1982, 'F'),
('aladar', 'aladár.dunai@mail.hu', 'Dunai Aladár', 1980, 'F'),
('alexandra', 'alexandra.bagóczki@mail.hu', 'Bagóczki Alexandra', 1992, 'N'),
('alexis', 'alexbiro@gmail.com', 'Biró Alexander', 2000, 'F'),
('andi', 'andrea.maródi@mail.hu', 'Maródi Andrea', 1968, 'N'),
('andras2', 'andrás.tóth@mail.hu', 'Tóth András', 1997, 'F'),
('andras21', 'andrás.molnár@mail.hu', 'Molnár András', 1977, 'F'),
('andras3', 'andrás.vígh@mail.hu', 'Vígh András', 1971, 'F'),
('andras4', 'andras4@gmail.com', 'Back András', 1984, 'F'),
('andras41', 'andras41@gmail.com', 'Komjáti András', 1997, 'F'),
('ANDRASE', 'ANDRASE@gmail.com', 'Erdei András', 1997, 'F'),
('ANDRASN', 'andrás.nagy@mail.hu', 'Nagy András', 1980, 'F'),
('andrea', 'andrea.kiss@mail.hu', 'Kiss Andrea', 1993, 'N'),
('andrea3', 'andrea3@gmail.com', 'Szomor Andrea', 1996, 'N'),
('andrea4', 'andrea4@gmail.com', 'Neizer Andrea', 1981, 'N'),
('ANDREAT', 'ANDREAT@gmail.com', 'Tornyos Andrea', 1986, 'N'),
('anett3', 'anett.pivarcsi@mail.hu', 'Pivarcsi Anett', 1967, 'N'),
('aniko', 'aniko@gmail.com', 'Tóth Anikó', 1973, 'N'),
('aniko4', 'aniko4@gmail.com', 'Böröcz Anikó', 1978, 'N'),
('ANIKOS', 'ANIKOS@gmail.com', 'Simon Anikó', 1988, 'N'),
('anita', 'anita.hamvay-kovács@mail.hu', 'Hamvay-Kovács Anita', 1971, 'N'),
('annamaria1', 'annamária.szűcs@mail.hu', 'Szűcs Annamária', 1990, 'N'),
('ANNAMARIAR', 'ANNAMARIAR@gmail.com', 'Regős Annamária', 1977, 'N'),
('aron2', 'aron2@gmail.com', 'Jakab Áron', 1971, 'F'),
('ARONK', 'áron.kelemen@mail.hu', 'Kelemen Áron', 1989, 'F'),
('arpad2', 'árpád.ötvös@mail.hu', 'Ötvös Árpád', 1990, 'F'),
('ARPADH', 'árpád.horváth@mail.hu', 'Horváth Árpád', 1990, 'F'),
('ARPADM', 'árpád.móricz@mail.hu', 'Móricz Árpád', 1986, 'F'),
('attila', 'attila@gmail.com', 'Csóti Attila', 1979, 'F'),
('attila1', 'attila.gulyás@mail.hu', 'Gulyás Attila', 1982, 'F'),
('attila4', 'attila.baróti@mail.hu', 'Baróti Attila', 1975, 'F'),
('ATTILAO', 'ATTILAO@gmail.com', 'Opra Attila', 1995, 'F'),
('balazs1', 'balázs.bozsik@mail.hu', 'Bozsik Balázs', 1992, 'F'),
('balazs2', 'balázs.szűcs@mail.hu', 'Szűcs Balázs', 1984, 'F'),
('balazs3', 'balazs3@gmail.com', 'Bakódy Balázs', 1986, 'F'),
('balint', 'balint@gmail.com', 'Horváth Bálint', 1996, 'F'),
('balint1', 'balint1@gmail.com', 'Molnár Bálint', 1989, 'F'),
('balint2', 'balint2@gmail.com', 'Vukasinovity Bálint', 1997, 'F'),
('balu', 'bálint.endresz@mail.hu', 'Endresz Bálint', 1976, 'F'),
('beata4', 'beáta.bagi@mail.hu', 'Bagi Beáta', 1994, 'N'),
('BEATRIXK', 'beatrix.kerényi@mail.hu', 'Kerényi Beatrix', 1972, 'N'),
('BEATRIXS', 'beatrix.szekendi@mail.hu', 'Szekendi Beatrix', 1981, 'N'),
('BELAF', 'BELAF@gmail.com', 'Farkas Béla', 1995, 'F'),
('bence', 'bence@gmail.com', 'Győrffy Bence', 1987, 'F'),
('BENCEB', 'bence.bajusz@mail.hu', 'Bajusz Bence', 1973, 'F'),
('bernadett1', 'bernadett1@gmail.com', 'Simon Bernadett', 1984, 'N'),
('bernadett2', 'bernadett.kovács@mail.hu', 'Kovács Bernadett', 1996, 'N'),
('BERNADETTO', 'bernadett.orbán@mail.hu', 'Orbán Bernadett', 1987, 'N'),
('bertalan', 'bertalan@gmail.com', 'Csiger Bertalan', 1977, 'F'),
('brigitta', 'brigitta.székely@mail.hu', 'Székely Brigitta', 1978, 'N'),
('brigitta3', 'brigitta.pataki@mail.hu', 'Pataki Brigitta', 1991, 'N'),
('csongor3', 'csongor.nagymihály@mail.hu', 'Nagymihály Csongor', 1984, 'F'),
('dani', 'daniel@gmail.com', 'Vörös Dániel', 1986, 'F'),
('daniel', 'dániel.rácz@mail.hu', 'Rácz Dániel', 1978, 'F'),
('daniel1', 'dániel.keszler@mail.hu', 'Keszler Dániel', 1969, 'F'),
('david', 'david@gmail.com', 'Ambrus Dávid', 1974, 'F'),
('david1', 'david1@gmail.com', 'Sobják Dávid', 1970, 'F'),
('david4', 'david4@gmail.com', 'Berta Dávid', 1990, 'F'),
('debora', 'debóra.barna@mail.hu', 'Barna Debóra', 1976, 'N'),
('denes', 'denes@gmail.com', 'Tömböly Dénes', 1975, 'F'),
('desdemona', 'mor.otto@mail.hu', 'Mór Ottó', 1968, 'F'),
('dora3', 'dóra.sarodi@mail.hu', 'Sarodi Dóra', 1995, 'N'),
('edit', 'edit.bittmann@mail.hu', 'Bittmann Edit', 1984, 'N'),
('emese', 'emese.kuruc@mail.hu', 'Kuruc Emese', 1989, 'N'),
('eszter', 'eszter.molnár@mail.hu', 'Molnár Eszter', 1987, 'N'),
('eszter2', 'eszter.balogh@mail.hu', 'Balogh Eszter', 1998, 'N'),
('eszter4', 'eszter.fülöp@mail.hu', 'Fülöp Eszter', 1993, 'N'),
('ESZTERE', 'eszter.érsek@mail.hu', 'Érsek Eszter', 1978, 'N'),
('eva', 'eva@gmail.com', 'Enyedi Éva', 1967, 'N'),
('eva2', 'eva2@gmail.com', 'Perlinger Éva', 1971, 'N'),
('EVAV', 'EVAV@gmail.com', 'Viktor Éva', 1980, 'N'),
('ferenc1', 'ferenc.orosz@mail.hu', 'Orosz Ferenc', 1983, 'F'),
('fruzsina4', 'fruzsina4@gmail.com', 'Frank Fruzsina', 1996, 'N'),
('gabor1', 'gabor1@gmail.com', 'Köves Gábor', 1973, 'F'),
('gabor4', 'gábor.telek@mail.hu', 'Telek Gábor', 1987, 'F'),
('GABORS', 'GABORS@gmail.com', 'Szöllősi Gábor', 1990, 'F'),
('gabriella1', 'gabriella1@gmail.com', 'Nagy Gabriella', 1982, 'N'),
('gabriella10', 'gabriella10@gmail.com', 'Vida Gabriella', 1969, 'N'),
('georgij', 'georgij.nyíri@mail.hu', 'Nyíri Georgij', 1983, 'F'),
('gusztav', 'gusztav@gmail.com', 'Bárci Gusztáv', 1967, 'F'),
('GYONGYIK', 'gyöngyi.kornseé@mail.hu', 'Kornseé Gyöngyi', 1974, 'N'),
('GYORGYO', 'GYORGYO@gmail.com', 'Oroszi György', 1980, 'F'),
('henrik3', 'henrik.nádudvari@mail.hu', 'Nádudvari Henrik', 1986, 'F'),
('IBOLYAA', 'ibolya.andor@mail.hu', 'Andor Ibolya', 1983, 'N'),
('ilona3', 'ilona3@gmail.com', 'Bosnyák Ilona', 1990, 'N'),
('imre', 'imre.búza@mail.hu', 'Búza Imre', 1988, 'F'),
('imre1', 'imre.papp@mail.hu', 'Papp Imre', 1976, 'F'),
('istvan', 'istvan@gmail.com', 'Soós István', 1986, 'F'),
('istvan1', 'istván.vizi@mail.hu', 'Vizi István', 1997, 'F'),
('ISTVANV', 'ISTVANV@gmail.com', 'Varga István', 1989, 'F'),
('janos3', 'janos3@gmail.com', 'Harangozó János', 1967, 'F'),
('JANOSG', 'JANOSG@gmail.com', 'Giliga János', 1975, 'F'),
('JANOSP', 'JANOSP@gmail.com', 'Pálinkás János', 1984, 'F'),
('jozsef', 'jozsef@gmail.com', 'Gergely József', 1985, 'F'),
('jozsef2', 'józsef.vajda@mail.hu', 'Vajda József', 1978, 'F'),
('JOZSEFG', 'józsef.gyuris@mail.hu', 'Gyuris József', 1975, 'F'),
('JUDITH', 'JUDITH@gmail.com', 'Hídasi Judit', 1997, 'N'),
('julia', 'julia@gmail.com', 'Tóth Júlia', 1993, 'N'),
('julia4', 'julia4@gmail.com', 'Nagy Júlia', 1985, 'N'),
('julianna4', 'julianna4@gmail.com', 'Szabó Julianna', 1990, 'N'),
('kanita12', 'anita.kiss12@gmail.com', 'Kiss Anita', 1975, 'N'),
('kata', 'katalin.gondos@mail.hu', 'Gondos Katalin', 1968, 'N'),
('katalin', 'katalin.horváth@mail.hu', 'Horváth Katalin', 1968, 'N'),
('katalin4', 'katalin4@gmail.com', 'Kertész Katalin', 1986, 'N'),
('kati', 'katalin.zatykó@mail.hu', 'Zatykó Katalin', 1995, 'N'),
('katka', 'katalin.kovács@mail.hu', 'Kovács Katalin', 1975, 'N'),
('klaudia2', 'klaudia.bakó@mail.hu', 'Bakó Klaudia', 1982, 'N'),
('kornel4', 'kornél.lukács@mail.hu', 'Lukács Kornél', 1975, 'F'),
('kristof4', 'kristof4@gmail.com', 'Poprádi Kristóf', 1984, 'F'),
('kriszti', 'kriszti@gmail.com', 'Horváth Krisztina', 1978, 'N'),
('krisztian4', 'krisztián.czérna@mail.hu', 'Czérna Krisztián', 1970, 'F'),
('KRISZTIANM', 'KRISZTIANM@gmail.com', 'Mogyródi Krisztián', 1968, 'F'),
('krisztina', 'krisztina@gmail.com', 'Szedlár Krisztina', 1979, 'N'),
('krisztina1', 'krisztina.bori@mail.hu', 'Bori Krisztina', 1969, 'N'),
('KRISZTINAG', 'KRISZTINAG@gmail.com', 'Gyárfás Krisztina', 1987, 'N'),
('lajos', 'lajos.kiss@mail.hu', 'Kiss Lajos', 1978, 'F'),
('lala', 'lajos.nagymihály@mail.hu', 'Nagymihály Lajos', 1997, 'F'),
('laszlo1', 'lászló.farkas@mail.hu', 'Farkas László', 1967, 'F'),
('laszlo2', 'lászló.móra@mail.hu', 'Móra László', 1975, 'F'),
('LASZLOA', 'lászló.antal@mail.hu', 'Antal László', 1969, 'F'),
('LASZLON', 'lászló.nagy@mail.hu', 'Nagy László', 1969, 'F'),
('maria1', 'mária.baráth@mail.hu', 'Baráth Mária', 1995, 'N'),
('mark', 'márk.kispál@mail.hu', 'Kispál Márk', 1996, 'F'),
('MARKH', 'márk.horváth@mail.hu', 'Horváth Márk', 1997, 'F'),
('marton', 'marton@gmail.com', 'Kalacsi Márton', 1989, 'F'),
('MATEK', 'máté.koza@mail.hu', 'Koza Máté', 1997, 'F'),
('matyas2', 'matyas2@gmail.com', 'Botka Mátyás', 1972, 'F'),
('MATYASS', 'mátyás.szilágyi@mail.hu', 'Szilágyi Mátyás', 1975, 'F'),
('melissza', 'nagy_peter@indamail.hu', 'Nagy Péter', 1998, 'F'),
('MIHALYJ', 'mihály.juhász@mail.hu', 'Juhász Mihály', 1979, 'F'),
('miklos2', 'miklos2@gmail.com', 'Gondos Miklós', 1995, 'F'),
('MIKLOSB', 'miklós.balla@mail.hu', 'Balla Miklós', 1979, 'F'),
('MONIKAM', 'mónika.mohos@mail.hu', 'Mohos Mónika', 1974, 'N'),
('NANDORF', 'nándor.fő@mail.hu', 'Fő Nándor', 1968, 'F'),
('nikolett3', 'nikolett3@gmail.com', 'Horváth Nikolett', 1981, 'N'),
('nikoletta4', 'nikoletta4@gmail.com', 'Kő Nikoletta', 1972, 'N'),
('NIKOLETTAT', 'nikoletta.tatár@mail.hu', 'Tatár Nikoletta', 1997, 'N'),
('norbert', 'norbert@gmail.com', 'Szűcs Norbert', 1969, 'F'),
('norbert2', 'norbert.hegedűs@mail.hu', 'Hegedűs Norbert', 1991, 'F'),
('norbert4', 'norbert4@gmail.com', 'Mile Norbert', 1983, 'F'),
('norbert5', 'norbert5@gmail.com', 'Béres Norbert', 1975, 'F'),
('pal', 'pál.barabás@mail.hu', 'Barabás Pál', 1968, 'F'),
('peter1', 'peter1@gmail.com', 'Kozma Péter', 1976, 'F'),
('peter2', 'peter2@gmail.com', 'Bozsó Péter', 1976, 'F'),
('peter3', 'peter3@gmail.com', 'Szalai Péter', 1983, 'F'),
('peter4', 'péter.bíró@mail.hu', 'Bíró Péter', 1985, 'F'),
('PETERB', 'péter.berendi@mail.hu', 'Berendi Péter', 1969, 'F'),
('polla', 'polla@gmail.com', 'Palágyi Polla', 1994, 'N'),
('rajmond4', 'rajmond.rácz@mail.hu', 'Rácz Rajmond', 1993, 'F'),
('reka4', 'réka.szikszai@mail.hu', 'Szikszai Réka', 1969, 'N'),
('RENATAK', 'renáta.kardos@mail.hu', 'Kardos Renáta', 1988, 'N'),
('RENATAS', 'RENATAS@gmail.com', 'Szirmai Renáta', 1991, 'N'),
('robert2', 'robert2@gmail.com', 'Patay Róbert', 1977, 'F'),
('ROBERTI', 'róbert.iván@mail.hu', 'Iván Róbert', 1967, 'F'),
('ROBERTP', 'ROBERTP@gmail.com', 'Pásztor Róbert', 1972, 'F'),
('roland', 'roland@gmail.com', 'Tóth Roland', 1968, 'F'),
('roland1', 'roland.ferencz@mail.hu', 'Ferencz Roland', 1985, 'F'),
('roza2', 'roza2@gmail.com', 'Bucskó Róza', 1988, 'N'),
('sandor', 'sandor@gmail.com', 'Karasz Sándor', 1970, 'F'),
('sandor3', 'sándor.farkas@mail.hu', 'Farkas Sándor', 1989, 'F'),
('sandor4', 'sandor4@gmail.com', 'Nagy Sándor', 1997, 'F'),
('sara', 'sára.farkas@mail.hu', 'Farkas Sára', 1973, 'N'),
('SEBASTIANF', 'SEBASTIANF@gmail.com', 'Foltényi Sebastián', 1992, 'F'),
('sebestyen', 'sebestyen@gmail.com', 'Rab Sebestyén', 1992, 'F'),
('szabolcs', 'szabolcs.bodor@mail.hu', 'Bodor Szabolcs', 1990, 'F'),
('SZABOLCSM', 'szabolcs.miklós@mail.hu', 'Miklós Szabolcs', 1980, 'F'),
('SZILARDS', 'szilárd.szalai@mail.hu', 'Szalai Szilárd', 1967, 'F'),
('szilvia1', 'szilvia.tari@mail.hu', 'Tari Szilvia', 1971, 'N'),
('tamara2', 'tamara.miklós@mail.hu', 'Miklós Tamara', 1980, 'N'),
('tamas', 'tamás.antal@mail.hu', 'Antal Tamás', 1984, 'F'),
('TAMASF', 'TAMASF@gmail.com', 'Fényes Tamás', 1997, 'F'),
('tibor', 'tibor.gombos@mail.hu', 'Gombos Tibor', 1993, 'F'),
('tibor2', 'tibor2@gmail.com', 'Dániel Tibor', 1985, 'F'),
('tihamer', 'tihamér.kazy@mail.hu', 'Kazy Tihamér', 1991, 'F'),
('timea', 'timea@gmail.com', 'Papós Tímea', 1996, 'N'),
('timea2', 'tímea.dusha@mail.hu', 'Dusha Tímea', 1975, 'N'),
('tunde', 'tunde@gmail.com', 'Turcsik Tünde', 1974, 'N'),
('valentin', 'valentin.feró@mail.hu', 'Feró Valentin', 1986, 'F'),
('veronika4', 'veronika4@gmail.com', 'Tankó Veronika', 1983, 'N'),
('VIKTORIAU', 'viktoria.urbán@mail.hu', 'Urbán Viktoria', 1996, 'N'),
('VIKTORK', 'viktor.keresztúri@mail.hu', 'Keresztúri Viktor', 1989, 'F'),
('vivien3', 'vivien3@gmail.com', 'Boros Vivien', 1991, 'N'),
('zoltan', 'zoltán.fodor@mail.hu', 'Fodor Zoltán', 1979, 'F'),
('zoltan4', 'zoltan4@gmail.com', 'Barna Zoltán', 1986, 'F'),
('ZOLTANP', 'zoltán.pintér@mail.hu', 'Pintér Zoltán', 1977, 'F'),
('ZOLTANT', 'zoltán.tóth@mail.hu', 'Tóth Zoltán', 1985, 'F'),
('zsofi1', 'zsofi1@gmail.com', 'Molnár Zsófi', 1983, 'N'),
('zsolt1', 'zsolt.pulai@mail.hu', 'Pulai Zsolt', 1988, 'F'),
('ZSOLTJ', 'ZSOLTJ@gmail.com', 'Józsa Zsolt', 1983, 'F'),
('zsuzsa', 'zsuzsanna@gmail.com', 'Pusztai Zsuzsanna', 1980, 'N'),
('zsuzsa3', 'zsuzsa.varsányi@mail.hu', 'Varsányi Zsuzsa', 1979, 'N'),
('zsuzsanna', 'zsuzsanna.barta@mail.hu', 'Barta Zsuzsanna', 1994, 'N'),
('ZSUZSAV', 'zsuzsa.vajda@mail.hu', 'Vajda Zsuzsa', 1976, 'N');

CREATE USER MASKED WITHOUT LOGIN;
GRANT SELECT ON Ugyfel TO MASKED;

EXECUTE AS User= 'MASKED';
SELECT * FROM Ugyfel;
REVERT

GRANT UNMASK TO MASKED

/*
SELECT 
    OBJECT_NAME(OBJECT_ID) AS TableName, 
    name, 
    is_masked, 
    masking_function 
FROM sys.masked_columns;
*/